language:
    python

python:
    - "2.7"
    - "pypy"

install:
    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip install -r requirements.txt

script: python tests/unittest_runner.py

branches:
  only:
      - master

notifications:
  recipients:
    - wallarelvo@gmail.com
  email:
    on_success: change
    on_failure: always
